# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a6b0e694891ccdff692445dd075172427b0c7c4567d898e2d5689e1474f5888948eab2b76527ea05aeb42151cd34bb5ddff6242f474c35000ada73ab7013d88

test:
  secret_key_base: 91146762aafa3a6a6c387ea40fa87a250af7835e11d125f6a9def3d04bd18a1674630f732656a4616dd37d4aca65f5f9557143fbee126439fb880db37fb43507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
